project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - psets/starter_code

format:
  html:
    theme: [cosmo, custom_theme.scss]
    css: styles.css
    toc: false
    include-in-header: header.html
    page-layout: full
    math: mathjax

website:
  favicon: favicon.ico
  navbar:    
    css: styles.css
    title: "Spring 2026"
    search: false
    left:
      - text: "Discord"
        href: https://discord.gg/dES3fSPEeC
      - text: "Gradescope"
        href: https://www.gradescope.com/courses/1091652
      - text: "Syllabus"
        href: syllabus.html
